// Generated by CoffeeScript 1.9.2
(function() {
  var initialize;

  initialize = function() {
    jQuery('document').find('[id^=map_canvas]').each(function(index) {
      console.log(this, index);
    });
  };

  window.onload = initialize;

}).call(this);
